import type {
  Agent,
  FooterSettings,
  NavigationSettings,
  PageContentMap,
  PageKey,
  PageRecord,
  Property,
  PropertyType,
  SiteSettings,
  TransactionType,
} from "@/lib/cms-types";

const exactTranslations = new Map<string, string>([
  ["Accueil", "Home"],
  ["Acheter", "Buy"],
  ["Achat", "Buy"],
  ["Louer", "Rent"],
  ["Location", "Rent"],
  ["/mois", "/month"],
  ["/jour", "/day"],
  ["/nuit", "/night"],
  ["Location journaliere", "Daily rent"],
  ["Location journaliere", "Daily rent"],
  ["Location quotidienne", "Daily rent"],
  ["A propos", "About"],
  ["Contact", "Contact"],
  ["Biens", "Properties"],
  ["Proprietes", "Properties"],
  ["Toutes les proprietes", "All properties"],
  ["Voir tout", "View all"],
  ["Voir le bien", "View property"],
  ["Explorer", "Explore"],
  ["Nos bureaux", "Our offices"],
  ["Message envoye", "Message sent"],
  ["Demande envoyee", "Request sent"],
  ["Envoyer", "Send"],
  ["Envoyer la demande", "Send request"],
  ["Envoyer une demande", "Send an inquiry"],
  ["Rechercher", "Search"],
  ["Rechercher des biens", "Search properties"],
  ["Type de transaction", "Transaction type"],
  ["Type de bien", "Property type"],
  ["Selectionner un type", "Select a type"],
  ["Selectionner un bien", "Select a property type"],
  ["Tous les types", "All types"],
  ["Tous les biens", "All properties"],
  ["Tous", "All"],
  ["Tous les types de biens", "All property types"],
  ["Toutes les villes", "All cities"],
  ["Prix min", "Min price"],
  ["Prix max", "Max price"],
  ["Biens en vedette seulement", "Featured properties only"],
  ["Effacer les filtres", "Clear filters"],
  ["Aucun bien trouve", "No property found"],
  ["Modifier vos filtres", "Adjust your filters"],
  ["Description", "Description"],
  ["Caracteristiques et prestations", "Features and amenities"],
  ["Enregistrer", "Save"],
  ["Partager", "Share"],
  ["Appeler", "Call"],
  ["Retour aux biens", "Back to properties"],
  ["Explorer plus", "Explore more"],
  ["Biens similaires", "Similar properties"],
  ["Chambres", "Bedrooms"],
  ["Salles de bain", "Bathrooms"],
  ["Surface", "Area"],
  ["Localisation", "Location"],
  ["Appartement", "Apartment"],
  ["Appartements", "Apartments"],
  ["Villa", "Villa"],
  ["Villas", "Villas"],
  ["Bureau", "Office"],
  ["Bureaux", "Offices"],
  ["Commercial", "Commercial"],
  ["Terrain", "Land"],
  ["Terrains", "Land"],
  ["Maison", "House"],
  ["Maisons", "Houses"],
  ["Penthouse", "Penthouse"],
  ["Studio", "Studio"],
  ["meuble", "furnished"],
  ["meublee", "furnished"],
  ["meubles", "furnished"],
  ["Climatisation", "Air conditioning"],
  ["Parking", "Parking"],
  ["Piscine", "Pool"],
  ["Jardin", "Garden"],
  ["Terrasse", "Terrace"],
  ["Balcon", "Balcony"],
  ["Cuisine equipee", "Equipped kitchen"],
  ["Securite", "Security"],
  ["Ascenseur", "Elevator"],
  ["Vue mer", "Sea view"],
  ["Centre-ville", "City center"],
  ["Californie", "California"],
  ["Tanger", "Tangier"],
  ["Rabat", "Rabat"],
  ["Marrakech", "Marrakech"],
  ["Casablanca", "Casablanca"],
  ["Maroc", "Morocco"],
  ["Tous droits reserves.", "All rights reserved."],
]);

const phraseTranslations: Array<[RegExp, string]> = [
  [/\bProprietaires \? Louez et vendez sans perte de temps\./gi, "Owners? Rent and sell without wasting time."],
  [/\bRemplir le formulaire\b/gi, "Fill out the form"],
  [/\bFormulaire\b/gi, "Form"],
  [/\bDefiler\b/gi, "Scroll"],
  [/\bVotre projet immobilier\b/gi, "Your real estate project"],
  [/\bNotre agence locale est a votre ecoute\b/gi, "Our local agency is here to listen"],
  [/\bprojets immobiliers\b/gi, "real estate projects"],
  [/\bChez MDK IMMOBILIER\b/gi, "At MDK IMMOBILIER"],
  [/\bNotre mission\b/gi, "Our mission"],
  [/\bsolutions technologiques\b/gi, "technology solutions"],
  [/\bexpertise de nos conseillers\b/gi, "expertise of our advisors"],
  [/\bexperience client unique et personnalisee\b/gi, "unique and personalized client experience"],
  [/\bReinventons ensemble votre experience immobiliere\./gi, "Together, let us reinvent your real estate experience."],
  [/\bUn echange direct avec notre equipe \?/gi, "Want a direct conversation with our team?"],
  [/\bNous sommes a votre ecoute\b/gi, "We are here to listen"],
  [/\bTrouvez votre investissement\b/gi, "Find your investment"],
  [/\bTrouvez votre\b/gi, "Find your"],
  [/\bde reve\b/gi, "of your dreams"],
  [/\bde rêve\b/gi, "of your dreams"],
  [/\bVivez dans le\b/gi, "Live in"],
  [/\bChoisissez votre style\b/gi, "Choose your style"],
  [/\bChoisissez votre experience\b/gi, "Choose your experience"],
  [/\bChoisissez une option\b/gi, "Choose an option"],
  [/\bTypes de proprietes\b/gi, "Property types"],
  [/\bProprietes a vendre\b/gi, "Properties for sale"],
  [/\bProprietes a louer\b/gi, "Properties for rent"],
  [/\bLocations journalieres\b/gi, "Daily rentals"],
  [/\bExperiences\b/gi, "Experiences"],
  [/\bChaque jour devient exceptionnel\b/gi, "Every day becomes exceptional"],
  [/\bChaque occasion\b/gi, "Every occasion"],
  [/\bIdeal pour\b/gi, "Ideal for"],
  [/\bServices haut de gamme\b/gi, "Premium services"],
  [/\bService de conciergerie\b/gi, "Concierge service"],
  [/\bChef prive disponible\b/gi, "Private chef available"],
  [/\bService chauffeur\b/gi, "Driver service"],
  [/\bMenage quotidien\b/gi, "Daily housekeeping"],
  [/\bOrganisation d['’]evenements\b/gi, "Event planning"],
  [/\bSecurite 24\/7\b/gi, "24/7 security"],
  [/\bAssistance 24\/7\b/gi, "24/7 support"],
  [/\bAvantages de la location\b/gi, "Rental benefits"],
  [/\bPourquoi louer avec\b/gi, "Why rent with"],
  [/\bPourquoi nous choisir\b/gi, "Why choose us"],
  [/\bUn accompagnement expert pour votre investissement\b/gi, "Expert support for your investment"],
  [/\bAnalyse du marche\b/gi, "Market analysis"],
  [/\bAccompagnement juridique\b/gi, "Legal support"],
  [/\bSolutions de financement\b/gi, "Financing solutions"],
  [/\bSelection active\b/gi, "Active selection"],
  [/\bDernieres opportunites a l['’]achat\b/gi, "Latest buying opportunities"],
  [/\bBiens disponibles a la location\b/gi, "Properties available for rent"],
  [/\bDernieres opportunites\b/gi, "Latest opportunities"],
  [/\bRetrouvez les annonces publiees les plus recentes\b/gi, "Browse the most recently published listings"],
  [/\bResultats filtres\b/gi, "Filtered results"],
  [/\bResultats\b/gi, "Results"],
  [/\bConditions flexibles\b/gi, "Flexible terms"],
  [/\bBiens verifies\b/gi, "Verified properties"],
  [/\bChaque bien est inspecte et verifie par notre equipe avant publication\./gi, "Every property is inspected and verified by our team before publication."],
  [/\bDurees de bail adaptables\b/gi, "Adaptable lease durations"],
  [/\bUne equipe dediee disponible\b/gi, "A dedicated team available"],
  [/\bEnvoyer le message\b/gi, "Send the message"],
  [/\bContactez notre equipe\b/gi, "Contact our team"],
  [/\bNous contacter\b/gi, "Contact us"],
  [/\bSelectionnez un type de bien\b/gi, "Select a property type"],
  [/\bSelectionnez\b/gi, "Select"],
  [/\bExplorez notre collection curatee\b/gi, "Explore our curated collection"],
  [/\bproprietes exceptionnelles\b/gi, "exceptional properties"],
  [/\bdisponibles a l['’]achat\b/gi, "available for purchase"],
  [/\bsummum du luxe immobilier\b/gi, "pinnacle of luxury real estate"],
  [/\bExperimentez la vie premium\b/gi, "Experience premium living"],
  [/\bselection curatee\b/gi, "curated selection"],
  [/\bproprietes a louer\b/gi, "properties for rent"],
  [/\boffrant la flexibilite\b/gi, "offering flexibility"],
  [/\bsans compromettre\b/gi, "without compromising"],
  [/\bl['’]elegance\b/gi, "elegance"],
  [/\blocations premium\b/gi, "premium rentals"],
  [/\bDe magnifiques retraites de vacances\b/gi, "From magnificent holiday retreats"],
  [/\blieux d['’]evenements sophistiques\b/gi, "sophisticated event venues"],
  [/\bdecouvrez des proprietes premium\b/gi, "discover premium properties"],
  [/\bdisponibles en location journaliere\b/gi, "available for daily rental"],
  [/\boptions exclusives de location journaliere\b/gi, "exclusive daily rental options"],
  [/\bservices et amenites concus\b/gi, "services and amenities designed"],
  [/\brendre chaque moment memorable\b/gi, "make every moment memorable"],
  [/\bVolume de ventes\b/gi, "Sales volume"],
  [/\bBiens vendus\b/gi, "Properties sold"],
  [/\bAgents experts\b/gi, "Expert agents"],
  [/\bAnnees d['’]experience\b/gi, "Years of experience"],
  [/\bDecouvrez\b/gi, "Discover"],
  [/\bExplorez\b/gi, "Explore"],
  [/\bSelectionnez\b/gi, "Select"],
  [/\bChoisissez\b/gi, "Choose"],
  [/\bExperimentez\b/gi, "Experience"],
  [/\bExperiences exclusives\b/gi, "Exclusive experiences"],
  [/\bexclusives\b/gi, "exclusive"],
  [/\bexceptionnelles\b/gi, "exceptional"],
  [/\binvestissement\b/gi, "investment"],
  [/\binvestissements\b/gi, "investments"],
  [/\bvotre\b/gi, "your"],
  [/\bVotre\b/g, "Your"],
  [/\bvos\b/gi, "your"],
  [/\bVos\b/g, "Your"],
  [/\bnotre\b/gi, "our"],
  [/\bNotre\b/g, "Our"],
  [/\bnos\b/gi, "our"],
  [/\bNos\b/g, "Our"],
  [/\bvous\b/gi, "you"],
  [/\bVous\b/g, "You"],
  [/\bnous\b/gi, "us"],
  [/\bNous\b/g, "We"],
  [/\bdisponible\b/gi, "available"],
  [/\bdisponibles\b/gi, "available"],
  [/\bequipe\b/gi, "team"],
  [/\bEquipe\b/g, "Team"],
  [/\bequipes\b/gi, "teams"],
  [/\bservice\b/gi, "service"],
  [/\bservices\b/gi, "services"],
  [/\bmarche\b/gi, "market"],
  [/\bjuridique\b/gi, "legal"],
  [/\bfinancement\b/gi, "financing"],
  [/\baccompagnement\b/gi, "support"],
  [/\bcurat[ée]e?\b/gi, "curated"],
  [/\bcompletes?\b/gi, "complete"],
  [/\bcomplete\b/gi, "complete"],
  [/\bcompletement\b/gi, "completely"],
  [/\bdecision\b/gi, "decision"],
  [/\bbien informee?\b/gi, "well informed"],
  [/\bassistance\b/gi, "assistance"],
  [/\bsereinement\b/gi, "with peace of mind"],
  [/\bavancer sereinement\b/gi, "move forward with confidence"],
  [/\bprocessus d['’]achat\b/gi, "purchase process"],
  [/\bprofil\b/gi, "profile"],
  [/\bobjectifs\b/gi, "objectives"],
  [/\badaptees\b/gi, "tailored"],
  [/\badaptables\b/gi, "adaptable"],
  [/\blongs sejours\b/gi, "long stays"],
  [/\bmissions professionnelles\b/gi, "business assignments"],
  [/\bbesoins saisonniers\b/gi, "seasonal needs"],
  [/\bparcours locatif\b/gi, "rental journey"],
  [/\bbail\b/gi, "lease"],
  [/\bDuree\b/g, "Duration"],
  [/\bduree\b/gi, "duration"],
  [/\bdurees\b/gi, "durations"],
  [/\bSauvegarder\b/gi, "Save"],
  [/\bAnnuler\b/gi, "Cancel"],
  [/\bModifier\b/gi, "Edit"],
  [/\bSupprimer\b/gi, "Delete"],
  [/\bAjouter\b/gi, "Add"],
  [/\bConfirmer\b/gi, "Confirm"],
  [/\bRefuser\b/gi, "Decline"],
  [/\bChargement\b/gi, "Loading"],
  [/\bChargement\.\.\./gi, "Loading..."],
  [/\bSucces\b/gi, "Success"],
  [/\bErreur\b/gi, "Error"],
  [/\bRetour\b/gi, "Back"],
  [/\bSuivant\b/gi, "Next"],
  [/\bPrecedent\b/gi, "Previous"],
  [/\bFermer\b/gi, "Close"],
  [/\bOuvrir\b/gi, "Open"],
  [/\bConnexion\b/gi, "Sign in"],
  [/\bDeconnexion\b/gi, "Sign out"],
  [/\bInscription\b/gi, "Sign up"],
  [/\bDecouvrez votre domaine\b/gi, "Discover your estate"],
  [/\bdomaine\b/gi, "estate"],
  [/\bUne agence fondee sur la\b/gi, "An agency built on"],
  [/\bagence fondee sur\b/gi, "agency built on"],
  [/\bfondee sur\b/gi, "built on"],
  [/\bfondee\b/gi, "founded"],
  [/\bSelection, accompagnement et execution\b/gi, "Selection, support and execution"],
  [/\bCe qui structure chaque mission\b/gi, "What structures every assignment"],
  [/\bNos valeurs\b/gi, "Our values"],
  [/\bNotre histoire\b/gi, "Our story"],
  [/\bClarte\b/gi, "Clarity"],
  [/\bDiscretion\b/gi, "Discretion"],
  [/\bExigence\b/gi, "Standards"],
  [/\bRecommandations argumentees\b/gi, "Reasoned recommendations"],
  [/\bprocessus lisibles\b/gi, "transparent processes"],
  [/\bpriorites nettes\b/gi, "clear priorities"],
  [/\bexecution respectueuse de la confidentialite\b/gi, "execution that respects confidentiality"],
  [/\bdossiers sensibles\b/gi, "sensitive matters"],
  [/\bselection rigoureuse\b/gi, "rigorous selection"],
  [/\bniveau de finition\b/gi, "level of finish"],
  [/\bcontrole avant publication\b/gi, "checked before publication"],
  [/\bSelection curatee\b/gi, "Curated selection"],
  [/\bAccompagnement sur mesure\b/gi, "Tailored support"],
  [/\bLecture precise du marche\b/gi, "Precise market reading"],
  [/\bExecution rapide et discrete\b/gi, "Fast and discreet execution"],
  [/\bMDK IMMOBILIER agit comme un partenaire de confiance\b/gi, "MDK IMMOBILIER acts as a trusted partner"],
  [/\bclients qui attendent plus qu['’]une simple recherche de biens\b/gi, "clients who expect more than a simple property search"],
  [/\bcadrer le besoin\b/gi, "frame the need"],
  [/\bfiltrer le marche\b/gi, "filter the market"],
  [/\bconstruire un parcours clair jusqu['’]a la signature\b/gi, "build a clear path through to signing"],
  [/\bqualite de portefeuille\b/gi, "portfolio quality"],
  [/\blecture du quartier\b/gi, "neighborhood analysis"],
  [/\bpotentiel patrimonial\b/gi, "long-term value potential"],
  [/\bqualite de service\b/gi, "service quality"],
  [/\bChaque recommandation est pensee pour reduire le bruit\b/gi, "Every recommendation is designed to reduce noise"],
  [/\baccelerer la bonne decision\b/gi, "speed up the right decision"],
  [/\bParlons de votre prochain\b/gi, "Let's discuss your next"],
  [/\bUne equipe disponible et reactive\b/gi, "A responsive and available team"],
  [/\bEnvoyer votre demande\b/gi, "Send your inquiry"],
  [/\bEnvoyer une demande\b/gi, "Send an inquiry"],
  [/\bEnvoyer le message\b/gi, "Send the message"],
  [/\bquelques details sur le type de bien\b/gi, "a few details about the property type"],
  [/\bvotre calendrier\b/gi, "your schedule"],
  [/\bpremiere orientation\b/gi, "initial guidance"],
  [/\boptions pertinentes\b/gi, "relevant options"],
  [/\bNous accompagnons\b/gi, "We support"],
  [/\bl['’]achat, la location et les experiences journalieres\b/gi, "the buying, renting and daily-rental experiences"],
  [/\bhaut de gamme\b/gi, "premium"],
  [/\bavec une approche plus precise\b/gi, "with a more precise approach"],
  [/\bplus discrete et plus exigeante\b/gi, "more discreet and more demanding"],
  [/\bAvantages\b/gi, "Benefits"],
  [/\brapidement\b/gi, "quickly"],
  [/\brapide\b/gi, "fast"],
  [/\bsouhaitez\b/gi, "wish to"],
  [/\bsouhaite\b/gi, "wish to"],
  [/\bpartenaire de confiance\b/gi, "trusted partner"],
  [/\bpartenaire\b/gi, "partner"],
  [/\brole\b/gi, "role"],
  [/\bbesoin\b/gi, "need"],
  [/\brecherche de biens\b/gi, "property search"],
  [/\brecherche\b/gi, "search"],
  [/\bsignature\b/gi, "signing"],
  [/\bportefeuille\b/gi, "portfolio"],
  [/\bquartier\b/gi, "neighborhood"],
  [/\bpatrimonial\b/gi, "long-term value"],
  [/\bqualite\b/gi, "quality"],
  [/\bdecision\b/gi, "decision"],
  [/\bbruit\b/gi, "noise"],
  [/\baccelerer\b/gi, "accelerate"],
  [/\bbonne\b/gi, "good"],
  [/\bbon\b/gi, "good"],
  [/\bdetails\b/gi, "details"],
  [/\bdetail\b/gi, "detail"],
  [/\bcalendrier\b/gi, "schedule"],
  [/\borientation\b/gi, "guidance"],
  [/\bpertinent\b/gi, "relevant"],
  [/\bpertinents\b/gi, "relevant"],
  [/\bpertinente\b/gi, "relevant"],
  [/\bpertinentes\b/gi, "relevant"],
  [/\bapproche\b/gi, "approach"],
  [/\bprecise\b/gi, "precise"],
  [/\bprecises\b/gi, "precise"],
  [/\bdiscret\b/gi, "discreet"],
  [/\bdiscrete\b/gi, "discreet"],
  [/\bdiscrets\b/gi, "discreet"],
  [/\bdiscretes\b/gi, "discreet"],
  [/\bexigeant\b/gi, "demanding"],
  [/\bexigeante\b/gi, "demanding"],
  [/\bexigeants\b/gi, "demanding"],
  [/\bexigeantes\b/gi, "demanding"],
  [/\baccompagnement\b/gi, "support"],
  [/\bAccompagnement\b/g, "Support"],
  [/\bsejour\b/gi, "stay"],
  [/\bsejours\b/gi, "stays"],
  [/\bevenement\b/gi, "event"],
  [/\bevenements\b/gi, "events"],
  [/\bsaisonnier\b/gi, "seasonal"],
  [/\bsaisonniers\b/gi, "seasonal"],
  [/\bsaisonniere\b/gi, "seasonal"],
  [/\bsaisonnieres\b/gi, "seasonal"],
  [/\bdernier\b/gi, "latest"],
  [/\bderniere\b/gi, "latest"],
  [/\bderniers\b/gi, "latest"],
  [/\bdernieres\b/gi, "latest"],
  [/\bopportunite\b/gi, "opportunity"],
  [/\bopportunites\b/gi, "opportunities"],
  [/\bvendre\b/gi, "sell"],
  [/\bventes\b/gi, "sales"],
  [/\bclient\b/gi, "client"],
  [/\bclients\b/gi, "clients"],
  [/\bquotidien\b/gi, "daily"],
  [/\bquotidienne\b/gi, "daily"],
  [/\bsejour\b/gi, "stay"],
  [/\bjournalier\b/gi, "daily"],
  [/\bjournaliere\b/gi, "daily"],
  [/\bjournalieres\b/gi, "daily"],
  [/\bjournaliers\b/gi, "daily"],
  [/\bne\s+([a-zA-ZÀ-ÿ'’]+)\s+pas\b/gi, "not $1"],
  [/\bplus precise\b/gi, "more precise"],
  [/\bplus discrete\b/gi, "more discreet"],
  [/\bplus exigeante\b/gi, "more demanding"],
  [/\bcette\b/gi, "this"],
  [/\bces\b/gi, "these"],
  [/\bquand\b/gi, "when"],
  [/\bcomment\b/gi, "how"],
  [/\bpourquoi\b/gi, "why"],
  [/\btelephone\b/gi, "phone"],
  [/\bTelephone\b/g, "Phone"],
  [/\be-mail\b/gi, "email"],
  [/\bOption choisie\b/gi, "Selected option"],
  [/\bOption selectionnee\b/gi, "Selected option"],
  [/\bChoisissez une option\b/gi, "Choose an option"],
  [/\bQuel accompagnement recherchez-vous \?/gi, "What support are you looking for?"],
  [/\bLouer votre bien\b/gi, "Rent out your property"],
  [/\bConfier la gestion locative de votre bien\b/gi, "Entrust your rental management to us"],
  [/\bLa gestion locative\b/gi, "Rental management"],
  [/\bDecrivez votre projet immobilier\b/gi, "Describe your real estate project"],
  [/\bVotre nom\b/gi, "Your name"],
  [/\bNom complet\b/gi, "Full name"],
  [/\bVotre message\b/gi, "Your message"],
  [/\bAjoutez un detail utile pour notre equipe\b/gi, "Add any useful detail for our team"],
  [/\bPrecedent\b/gi, "Previous"],
  [/\bSuivant\b/gi, "Next"],
  [/\bEnvoi\.\.\./gi, "Sending..."],
  [/\bMerci\. Notre equipe vous recontactera rapidement\./gi, "Thank you. Our team will contact you shortly."],
  [/\bMerci, notre equipe revient vers vous rapidement\./gi, "Thank you, our team will get back to you shortly."],
  [/\bVotre projet a bien ete transmis\./gi, "Your project has been submitted."],
  [/\baccompagnement adapte a votre besoin\b/gi, "support adapted to your needs"],
  [/\bJe suis interesse par\b/gi, "I am interested in"],
  [/\bPouvez-vous me contacter \?/gi, "Can you contact me?"],
  [/\borganiser une visite\b/gi, "schedule a viewing"],
  [/\bBonjour\b/gi, "Hello"],
  [/\bMerci de me contacter\b/gi, "Please contact me"],
  [/\bContactez-nous\b/gi, "Contact us"],
  [/\bcontactera rapidement\b/gi, "will contact you shortly"],
  [/\bNos biens\b/gi, "Our properties"],
  [/\bbiens trouves\b/gi, "properties found"],
  [/\bbien trouve\b/gi, "property found"],
  [/\bParcourez\b/gi, "Browse"],
  [/\bannonces immobilieres\b/gi, "real estate listings"],
  [/\bfiltrees\b/gi, "filtered"],
  [/\bsur\b/gi, "on"],
  [/\ba votre ecoute\b/gi, "ready to help"],
  [/\ba votre\b/gi, "at your"],
  [/\bavec\b/gi, "with"],
  [/\bpour\b/gi, "for"],
  [/\bet\b/gi, "and"],
  [/\bou\b/gi, "or"],
  [/\bde\b/gi, "of"],
  [/\bdes\b/gi, "of"],
  [/\bdu\b/gi, "of"],
  [/\bla\b/gi, "the"],
  [/\ble\b/gi, "the"],
  [/\bles\b/gi, "the"],
  [/\bun\b/gi, "a"],
  [/\bune\b/gi, "a"],
  [/\bimmobilier\b/gi, "real estate"],
  [/\bimmobiliere\b/gi, "real estate"],
  [/\bimmobilieres\b/gi, "real estate"],
  [/\bluxe\b/gi, "luxury"],
  [/\bcentre-ville\b/gi, "city center"],
  [/\bcentre ville\b/gi, "city center"],
  [/\bchambre\b/gi, "bedroom"],
  [/\bchambres\b/gi, "bedrooms"],
  [/\bsalle de bain\b/gi, "bathroom"],
  [/\bsalles de bain\b/gi, "bathrooms"],
  [/\bpropriete\b/gi, "property"],
  [/\bproprietes\b/gi, "properties"],
  [/\bbien\b/gi, "property"],
  [/\bbiens\b/gi, "properties"],
  [/\bachetez\b/gi, "buy"],
  [/\bachat\b/gi, "purchase"],
  [/\blouez\b/gi, "rent"],
  [/\bvendez\b/gi, "sell"],
  [/\bvente\b/gi, "sale"],
  [/\blocation journaliere\b/gi, "daily rental"],
  [/\blocation\b/gi, "rental"],
  [/\bjournalier\b/gi, "daily"],
  [/\bjournaliere\b/gi, "daily"],
  [/\bdisponibles\b/gi, "available"],
  [/\bdisponible\b/gi, "available"],
  [/\bmodifiez\b/gi, "adjust"],
  [/\bfiltres\b/gi, "filters"],
  [/\brecherche\b/gi, "search"],
  [/\bmot-cle\b/gi, "keyword"],
  [/\bville\b/gi, "city"],
  [/\bvilles\b/gi, "cities"],
  [/\badresse\b/gi, "address"],
  [/\bAdresse\b/g, "Address"],
  [/\bcaracteristiques\b/gi, "features"],
  [/\bprestations\b/gi, "amenities"],
  [/\bsimilaire\b/gi, "similar"],
  [/\bsimilaires\b/gi, "similar"],
  [/\bagence\b/gi, "agency"],
  [/\bequipe\b/gi, "team"],
  [/\bclient\b/gi, "client"],
  [/\bclients\b/gi, "clients"],
  [/\bpersonnalisee\b/gi, "personalized"],
  [/\blocale\b/gi, "local"],
  [/\blocal\b/gi, "local"],
  [/\bprojet\b/gi, "project"],
  [/\bprojets\b/gi, "projects"],
  [/\baccompagnement\b/gi, "support"],
  [/\bexperts\b/gi, "experts"],
  [/\bexpertise\b/gi, "expertise"],
];

// Keys whose values are never translated (URLs, slugs, emails, phones, IDs, codes).
// Exported so the Gemini translation service reuses the exact same exclusion list.
export const skipKeys = new Set([
  "href",
  "ctaHref",
  "primaryHref",
  "secondaryHref",
  "image",
  "images",
  "backgroundImage",
  "coverImage",
  "photoUrl",
  "imageUrl",
  "logoUrl",
  "defaultOgImage",
  "ogImage",
  "ogImageUrl",
  "video",
  "virtualTourUrl",
  "url",
  "email",
  "phone",
  "whatsapp",
  "whatsappNumber",
  "contactPhone",
  "contactEmail",
  "siteUrl",
  "slug",
  "routePath",
  "currencyCode",
  "currencyLocale",
]);

export function translateTextToEnglish(value: string | null | undefined) {
  if (value == null) return value;

  const exact = exactTranslations.get(value.trim());
  if (exact) return exact;

  let output = value;
  for (const [pattern, replacement] of phraseTranslations) {
    output = output.replace(pattern, replacement);
  }

  return output.replace(/\s+/g, " ").trim();
}

export function translateDeepToEnglish<T>(value: T, key?: string): T {
  if (typeof value === "string") {
    return (skipKeys.has(key ?? "") ? value : translateTextToEnglish(value)) as T;
  }

  if (Array.isArray(value)) {
    if (skipKeys.has(key ?? "")) return value;
    return value.map((item) => translateDeepToEnglish(item, key)) as T;
  }

  if (value && typeof value === "object") {
    const result: Record<string, unknown> = {};
    Object.entries(value as Record<string, unknown>).forEach(([childKey, childValue]) => {
      result[childKey] = translateDeepToEnglish(childValue, childKey);
    });
    return result as T;
  }

  return value;
}

export function translateNavLinksToEnglish(links: NavigationSettings["links"]) {
  return links.map((link) => ({
    ...link,
    label: translateTextToEnglish(link.label) ?? link.label,
  }));
}

export function translateSiteSettingsToEnglish(input: SiteSettings) {
  return {
    siteDescription: translateTextToEnglish(input.siteDescription),
    siteKeywords: input.siteKeywords.map((keyword) => translateTextToEnglish(keyword) ?? keyword),
    copyrightText: translateTextToEnglish(input.copyrightText),
    defaultSeoTitle: translateTextToEnglish(input.defaultSeoTitle),
    defaultSeoDescription: translateTextToEnglish(input.defaultSeoDescription),
  };
}

export function translateNavigationToEnglish(input: NavigationSettings) {
  return {
    logoAlt: translateTextToEnglish(input.logoAlt),
    links: translateNavLinksToEnglish(input.links),
  };
}

export function translateFooterToEnglish(input: FooterSettings) {
  return {
    brandText: translateTextToEnglish(input.brandText),
    quickLinks: translateNavLinksToEnglish(input.quickLinks),
    propertyLinks: translateNavLinksToEnglish(input.propertyLinks),
    legalLinks: translateNavLinksToEnglish(input.legalLinks),
  };
}

export function translateTransactionTypeToEnglish(input: Omit<TransactionType, "id"> | TransactionType) {
  return {
    label: translateTextToEnglish(input.label),
    description: translateTextToEnglish(input.description),
    navLabel: translateTextToEnglish(input.navLabel),
    priceSuffix: translateTextToEnglish(input.priceSuffix),
  };
}

export function translatePropertyTypeToEnglish(input: Omit<PropertyType, "id"> | PropertyType) {
  return {
    label: translateTextToEnglish(input.label),
    description: translateTextToEnglish(input.description),
  };
}

export function translateAgentToEnglish(input: Omit<Agent, "id" | "createdAt" | "updatedAt"> | Agent) {
  return {
    role: translateTextToEnglish(input.role),
    bio: translateTextToEnglish(input.bio),
    seoTitle: translateTextToEnglish(input.seoTitle),
    seoDescription: translateTextToEnglish(input.seoDescription),
  };
}

export function translatePropertyToEnglish(
  input: Omit<
    Property,
    | "id"
    | "transactionType"
    | "propertyType"
    | "transactionTypeSlug"
    | "propertyTypeSlug"
    | "createdAt"
    | "updatedAt"
    | "agent"
  > | Property
) {
  return {
    title: translateTextToEnglish(input.title),
    neighborhood: translateTextToEnglish(input.neighborhood),
    fullAddress: translateTextToEnglish(input.fullAddress),
    shortDescription: translateTextToEnglish(input.shortDescription),
    longDescription: translateTextToEnglish(input.longDescription),
    features: input.features.map((feature) => translateTextToEnglish(feature) ?? feature),
    seoTitle: translateTextToEnglish(input.seoTitle),
    seoDescription: translateTextToEnglish(input.seoDescription),
  };
}

export function translatePageRecordToEnglish<TPageKey extends PageKey>(
  input: PageRecord<TPageKey>
): Pick<PageRecord<TPageKey>, "title" | "seoTitle" | "seoDescription" | "content"> {
  return {
    title: translateTextToEnglish(input.title) ?? input.title,
    seoTitle: translateTextToEnglish(input.seoTitle),
    seoDescription: translateTextToEnglish(input.seoDescription),
    content: translateDeepToEnglish<PageContentMap[TPageKey]>(input.content),
  };
}
